version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: office-ui-fabric-react
    versions:
    - 7.157.2
    - 7.158.0
    - 7.158.1
    - 7.158.2
    - 7.158.3
    - 7.159.0
    - 7.160.0
    - 7.160.1
    - 7.160.2
    - 7.160.3
    - 7.161.0
    - 7.162.0
    - 7.162.1
    - 7.163.0
    - 7.164.0
    - 7.164.1
    - 7.164.2
    - 7.165.0
    - 7.165.1
    - 7.165.2
    - 7.166.0
    - 7.166.1
    - 7.166.2
    - 7.168.0
    - 7.168.1
  - dependency-name: "@microsoft/rush-stack-compiler-3.3"
    versions:
    - 0.9.38
    - 0.9.39
    - 0.9.40
    - 0.9.41
    - 0.9.42
    - 0.9.43
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 7.2.4
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: "@microsoft/sp-lodash-subset"
    versions:
    - 1.11.0
    - 1.12.0
  - dependency-name: "@microsoft/sp-core-library"
    versions:
    - 1.11.0
    - 1.12.0
  - dependency-name: "@microsoft/sp-office-ui-fabric-core"
    versions:
    - 1.11.0
    - 1.12.0
  - dependency-name: "@microsoft/sp-module-interfaces"
    versions:
    - 1.11.0
    - 1.12.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
